channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.1.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==1.26.2
  - packaging==23.2
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
